### ISSUE TITLE
Configuring socket.io

### ISSUE THREAD

**Issue by slacktracer** [incompl/cloak#69]
How do I configure socket.io with cloak?
Am I totally missing something here? I usually do this with socket.io:
`io.set('transports', ['websocket']);`
`io.set('log level', 2);`
`io.enable('browser client minification');`
`io.enable('browser client etag');`
`io.enable('browser client gzip');`
How does it work with cloak?
I see that the log level can be set as cloak passes it straight to socket.io. How about everything else?
(sorry if my questions sound confused, I am confused about the socket.io/cloak relation/interaction...)

**Comment by incompl** [comment]
Works now!
